function grid = plotPanelMainGrid(parent, layoutSettings)
%PLOTPANELMAINGRID Common main grid for the plot panels: a 1x plot area
%plus a fixed-width sidebar column.
grid = uigridlayout(parent, ...
    'RowHeight', {'1x'}, ...
    'ColumnWidth', {'1x', layoutSettings.DefaultSidebarWidth}, ...
    'ColumnSpacing', layoutSettings.DefaultColumnSpacing, ...
    'Padding', 0*ones(1,4), ...
    'Scrollable', false);
end
