classdef TyrePlotFrictionEllipsePanel < matlab.ui.componentcontainer.ComponentContainer
    %TYREPLOTFRICTIONELLIPSEPANEL Plots friction ellipse of tyre model.
    
    properties
        Model MagicFormulaTyre = MagicFormulaTyre.empty
    end
    properties (Access = private, Transient, NonCopyable)
        MainGrid                    matlab.ui.container.GridLayout
        Axes                        ui.FrictionEllipseAxes
        SidePanel                   matlab.ui.container.Panel
        SidePanelGrid               matlab.ui.container.GridLayout
    end
    properties (Access = private)
        Settings settings.AppSettings
        SettingsChangedListener event.listener
    end
    events (NotifyAccess = public)
        TyreModelChanged
        TyreDataChanged
    end
    methods (Access = private)
        function onModelChanged(obj, ~, event)
            model = event.Model;
            obj.Model = model;
            obj.Axes.Model = model;
        end
        function onDataChanged(obj, ~, event)
            % TODO: data not used as of now.
        end
        function onPlotSettingsChanged(obj, source, event)
            s = obj.Settings;
            s = s.View.TyreAnalysisPanel.TyrePlotFrictionEllipsePanel;
            tag = source.Tag;
            value = event.Value;
            switch tag
                case 'XLimit'
                    s.Limits(1) = value;
                case 'YLimit'
                    s.Limits(2) = value;
                case 'MaxLONGSLIP'
                    %Widgets hold percent; settings hold slip ratio.
                    s.LONGSLIP_Max = value/100;
                case 'StepLONGSLIP'
                    s.LONGSLIP_Step = value/100;
                otherwise
                    s.(settingsNameFromTag(tag)) = value;
            end
            refresh(obj.Axes)
        end
        function onSteadyStateSettingsChanged(obj, source, event)
            s = obj.Settings;
            s = s.View.TyreAnalysisPanel.TyrePlotFrictionEllipsePanel;
            tag = source.Tag;
            value = event.Value;
            switch tag
                case 'INFLPRES'
                    s.INFLPRES = helpers.bar2pascal(value);
                case 'INCLANGL'
                    s.INCLANGL = deg2rad(value);
                case 'FZW'
                    s.FZW = value;
                case 'TYRESIDE'
                    s.TYRESIDE = value;
            end
            refresh(obj.Axes)
        end
    end
    methods (Access = private, Static)
        function name = settingsNameFromTag(tag)
            %Widget tags equal the settings property names except for
            %these renames.
            renameMap = struct( ...
                'MaxSLIPANGL', 'SLIPANGL_Max', ...
                'StepSLIPANGL', 'SLIPANGL_Step');
            if isfield(renameMap, tag)
                name = renameMap.(tag);
            else
                name = tag;
            end
        end
    end
    methods(Access = protected)
        function setupSidePanel(obj)
            obj.SidePanel = uipanel(obj.MainGrid);
            
            obj.SidePanelGrid = uigridlayout(obj.SidePanel, ...
                'RowHeight', repmat({'fit'}, 1, 2), ...
                'ColumnWidth', {'1x'}, ...
                'ColumnSpacing', 0, ...
                'Padding', zeros(1,4), ...
                'Scrollable', true);
        end
        function setupPlotSettings(obj)
            s = obj.Settings;
            p = uipanel(obj.SidePanelGrid, ...
                'Title', 'Plot Settings', ...
                'FontWeight', settings.TextSettings.FontWeightPanel, ...
                'FontName', settings.TextSettings.FontNamePanel, ...
                'BorderType', 'none');
            w = settings.LayoutSettings.DefaultButtonWidthTextIcon;
            g = uigridlayout(p, ...
                'RowHeight', repmat({'fit'}, 1, 9), ...
                'ColumnWidth', {w, 'fit'}, ...
                'ColumnSpacing', settings.LayoutSettings.DefaultColumnSpacing, ...
                'Padding', settings.LayoutSettings.DefaultPadding, ...
                'Scrollable', false);
            
            s = s.View.TyreAnalysisPanel.TyrePlotFrictionEllipsePanel;
            uibutton(g, 'state', 'Text', 'Equal', ...
                'Tag', 'AxisEqual', ...
                'Value', s.AxisEqual, ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged);
            uilabel(g, 'Text', 'Axis');

            uibutton(g, 'state', 'Text', 'Manual', ...
                'Tag', 'AxisManualLimits', ...
                'Value', s.AxisManualLimits, ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged);
            uilabel(g, 'Text', 'Limits');

            uieditfield(g, 'numeric', ...
                'Tag', 'XLimit', ...
                'ValueDisplayFormat', '%.0f [N]', ...
                'Value', s.Limits(1), ...
                'Limits', [0 100E3], 'LowerLimitInclusive', false, ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged);
            uilabel(g, 'Text', 'X-Limit');

            uieditfield(g, 'numeric', ...
                'Tag', 'YLimit', ...
                'ValueDisplayFormat', '%.0f [N]', ...
                'Value', s.Limits(2), ...
                'Limits', [0 100E3], 'LowerLimitInclusive', false, ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged);
            uilabel(g, 'Text', 'Y-Limit');

            uieditfield(g, 'numeric', ...
                'Tag', 'MaxSLIPANGL', ...
                'Limits', [-90 90], ...
                'Value', s.SLIPANGL_Max, ...
                'ValueDisplayFormat', '%.1f [deg]', ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged);
            uilabel(g, 'Text', 'SLIPANGL (Max)');

            uieditfield(g, 'numeric', ...
                'Tag', 'StepSLIPANGL', ...
                'Limits', [-90 90], ...
                'Value', s.SLIPANGL_Step, ...
                'ValueDisplayFormat', '%.1f [deg]', ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged);
            uilabel(g, 'Text', 'SLIPANGL (Step)');

            uieditfield(g, 'numeric', ...
                'Tag', 'MaxLONGSLIP', ...
                'Limits', [-1 1]*100, ...
                'Value', s.LONGSLIP_Max, ...
                'ValueDisplayFormat', '%.1f [%%]', ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged);
            uilabel(g, 'Text', 'LONGSLIP (Max)');

            uieditfield(g, 'numeric', ...
                'Tag', 'StepLONGSLIP', ...
                'Limits', [-1 1]*100, ...
                'Value', s.LONGSLIP_Step, ...
                'ValueDisplayFormat', '%.1f [%%]', ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged);
            uilabel(g, 'Text', 'LONGSLIP (Step)');

            markers = {'none', '.', '+', 'o', '*', 'x', 'square', ...
                'diamond', '^', 'v', '>', '<', 'pentagram', 'hexagram'};
            uidropdown(g, 'Items', markers, ...
                'Value', s.Marker, ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged, ...
                'Tag', 'Marker');
            uilabel(g, 'Text', 'Marker');

            uispinner(g, ...
                'Limits', [0 100], 'LowerLimitInclusive', 'off', ...
                'Value', s.MarkerSize, ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged, ...
                'Tag', 'MarkerSize');
            uilabel(g, 'Text', 'Marker Size');

            uispinner(g, ...
                'Limits', [0 10], 'LowerLimitInclusive', 'off', ...
                'Value', s.LineWidth, ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged, ...
                'Tag', 'LineWidth');
            uilabel(g, 'Text', 'Line Width');
        end
        function setupSteadyStateSettings(obj)
            s = obj.Settings;
            p = uipanel(obj.SidePanelGrid, ...
                'Title', 'Steady-State Settings', ...
                'FontWeight', settings.TextSettings.FontWeightPanel, ...
                'FontName', settings.TextSettings.FontNamePanel, ...
                'BorderType', 'none');
            w = settings.LayoutSettings.DefaultButtonWidthTextIcon;
            g = uigridlayout(p, ...
                'RowHeight', repmat({'fit'}, 1, 6), ...
                'ColumnWidth', {'fit', w, 'fit'}, ...
                'ColumnSpacing', settings.LayoutSettings.DefaultColumnSpacing, ...
                'Padding', settings.LayoutSettings.DefaultPadding, ...
                'Scrollable', false);
            
            s = s.View.TyreAnalysisPanel.TyrePlotFrictionEllipsePanel;
            uilabel(g, 'Text', 'INCLANGL');
            uispinner(g, 'Step', 1, 'Limits', [-90 90], ...
                'Value', rad2deg(s.INCLANGL), ...
                'ValueChangedFcn', @obj.onSteadyStateSettingsChanged, ...
                'Tag', 'INCLANGL');
            uilabel(g, 'Text', '[deg]', ...
                'HorizontalAlignment', 'center');
            
            uilabel(g, 'Text', 'INFLPRES');
            uispinner(g, 'Step', 0.1, ...
                'ValueChangedFcn', @obj.onSteadyStateSettingsChanged, ...
                'Value', helpers.pascal2bar(s.INFLPRES), ...
                'Limits', [0 100], 'LowerLimitInclusive', 'off', ...
                'Tag', 'INFLPRES');
            uilabel(g, 'Text', '[bar]', ...
                'HorizontalAlignment', 'center');
            
            uilabel(g, 'Text', 'FZW');
            uispinner(g, 'Step', 100, ...
                'ValueChangedFcn', @obj.onSteadyStateSettingsChanged, ...
                'Value', s.FZW, ...
                'Limits', [0 100E3], 'LowerLimitInclusive', 'off', ...
                'Tag', 'FZW');
            uilabel(g, 'Text', '[N]', ...
                'HorizontalAlignment', 'center');
            
            uilabel(g, 'Text', 'TYRESIDE');
            uidropdown(g, 'Items', {'LEFT', 'RIGHT'}, ...
                'ItemsData', {0, 1}, ...
                'ValueChangedFcn', @obj.onSteadyStateSettingsChanged, ...
                'Value', s.TYRESIDE, ...
                'Tag', 'TYRESIDE');
        end
        function setupAxes(obj)
            ax = ui.FrictionEllipseAxes(obj.MainGrid, ...
                'Model', obj.Model);
            obj.Axes = ax;
        end
        function setupListeners(obj)
            addlistener(obj, 'TyreModelChanged', @obj.onModelChanged);
            addlistener(obj, 'TyreDataChanged', @obj.onDataChanged);
            s = obj.Settings.View.TyreAnalysisPanel;
            obj.SettingsChangedListener = listener(...
                s, 'SettingsChanged', @(~,~) obj.update());
        end
    end
    methods (Access = protected)
        function setup(obj)
            set(obj, 'Position', [0 0 800 400])
            obj.Settings = settings.AppSettings();
            obj.MainGrid = helpers.plotPanelMainGrid(obj, ...
                settings.LayoutSettings());
            setupAxes(obj)
            setupSidePanel(obj)
            setupPlotSettings(obj)
            setupSteadyStateSettings(obj)
            setupListeners(obj)
        end
        function update(obj)
            helpers.applySidebarLayout(obj.SidePanel, obj.Axes, ...
                obj.Settings.View.TyreAnalysisPanel.ShowSidebar);
        end
    end
end
